config/routes.rb
Rails.application.routes.draw do

  # TODO Clean this file up. Make it resourceful.

  devise_for :users, controllers: {invitations: 'invitations'}

  root 'home#index'

  resources :recordings
  resources :tags
  resources :links
  resources :utterances
  resources :clicks, only: [:create]

  get 'toggle_locale',                 to: 'home#toggle_locale',                 as: 'toggle_locale'
  post 'set_locale_cookie',            to: 'application#set_locale_cookie',      as: 'set_locale_cookie'

  post 'destroy_tags/:id',             to: 'tags#destroy_for_utterance',         as: 'destroy_tags'
  post 'destroy_links/:id',            to: 'links#destroy_for_utterance',        as: 'destroy_links'

  # Admin
  get 'admin',                         to: 'admin#index'
  get 'manage_recordings',             to: 'admin#manage_recordings',            as: 'manage_recordings'
  get 'tag_recording/:id',             to: 'admin#tag_recording',                as: 'tag_recording'
  get 'users',                         to: 'admin#users'
  get 'toggle_active/:id',             to: 'admin#toggle_active',                as: 'toggle_active'
  get 'toggle_can_record/:id',         to: 'admin#toggle_can_record',            as: 'toggle_can_record'
  get 'toggle_otp/:id',                to: 'admin#toggle_otp',                   as: 'toggle_otp'
  get 'add_caregiver',                 to: 'admin#add_caregiver'
  post 'create_share',                 to: 'admin#create_share'
  get 'new_registration',              to: 'admin#new_registration'
  post 'set_password',                 to: 'admin#set_password'
  post 'create_registration',          to: 'admin#create_registration'
  get 'switch_user_select',            to: 'admin#switch_user_select'
  post 'switch_to_user',               to: 'admin#switch_to_user'
  get 'new_caregiver',                 to: 'admin#new_caregiver'
  post 'create_caregiver',             to: 'admin#create_caregiver'
  get 'new_org',                       to: 'admin#new_org',                      as: 'new_org'
  post 'create_org',                   to: 'admin#create_org',                   as: 'create_org'
  post 'update_contact_email_address', to: 'admin#update_contact_email_address', as: 'update_contact_email_address'
  post 'update_redcap_id',             to: 'admin#update_redcap_id',             as: 'update_redcap_id'
  post 'update_phone_number',          to: 'admin#update_phone_number',          as: 'update_phone_number'
  post 'update_followup_message',      to: 'admin#update_followup_message',      as: 'update_followup_message'

  # Reports (Admin)
  get 'dashboard',                     to: 'reports#dashboard',                  as: 'dashboard'

  # Recording
  get 'record',                        to: 'record#new'
  get 'file_upload',                   to: 'record#file_upload',                 as: 'file_upload'
  post 'upload',                       to: 'record#upload',                      as: 'upload'
  post 'upload_file',                  to: 'record#upload_file',                 as: 'upload_file'
  get 'recording_saved',               to: 'record#saved'
  get 'upload_transcript',             to: 'record#upload_transcript',           as: 'upload_transcript'
  post 'create_utterances',            to: 'record#create_utterances',           as: 'create_utterances'

  # Recordings
  get 'get_metadata/:id',              to: 'recordings#get_metadata',            as: 'get_metadata'
  post 'update_metadata',              to: 'recordings#update_metadata',         as: 'update_metadata'
  get 'get_notes/:id',                 to: 'recordings#get_notes',               as: 'get_notes'
  post 'upsert_note',                  to: 'recordings#upsert_note',             as: 'upsert_note'
  post 'delete_note',                  to: 'recordings#delete_note',             as: 'delete_note'

  # Playback
  get 'play(/:id)',                    to: 'play#index',                         as: 'play'

  # Sharing
  resources :shares, controller: :share
  get 'no_shares',                     to: 'share#no_shares',                    as: 'no_shares'
  get 'twilio/sms',                    to: 'twilio#sms'

  # Help
  get 'help',                          to: 'help#index',                         as: 'help'
  get 'intro_video',                   to: 'help#intro_video',                   as: 'intro_video'
  get 'dont_onboard',                  to: 'help#dont_onboard',                  as: 'dont_onboard'
  get 'set_onboarded',                 to: 'help#set_onboarded',                 as: 'set_onboarded'
  get 'play/view_transcript/:id',      to: 'help#view_transcript',               as: 'view_transcript'

  # Analytics
  get 'analytics(/:id)',               to: 'analytics#index',                    as: 'analytics'

end

app/views/admin/_editable.html.haml
.editable
  .editable-display= value
  .open-editable-editor= inline_svg('edit.svg', class: 'editable-svg')
  .editable-editor.hidden{'data-post-path': post_path, 'data-user-id': user.id}
    %span= text_field_tag("editable_#{post_path}_#{user.id}", value, autofocus: true, placeholder: value, class: "editable-value #{input_class}")
    %span.update-editable= inline_svg('check.svg', class: 'editable-svg')
    %span.cancel-edit-editable= inline_svg('x.svg', class: 'editable-svg')

app/views/admin/_redcap_id.html.haml
- redcap_id = user.participant&.redcap_id
.redcap-id
  .redcap-id-display= redcap_id 
  .open-redcap-id-editor= inline_svg('edit.svg', class: 'redcap-id-svg')
  .redcap-id-editor.hidden{'data-user-id': user.id}
    %span= text_field_tag("redcap_id_#{user.id}", redcap_id, autofocus: true, placeholder: redcap_id, class: 'redcap-id-value')
    %span.update-redcap-id= inline_svg('check.svg', class: 'redcap-id-svg')
    %span.cancel-edit-redcap-id= inline_svg('x.svg', class: 'redcap-id-svg')

app/views/admin/add_caregiver.html.haml
.pad-30.horizontal-center
  #add-caregiver-to-existing-form.centered-form-container
    %p.form-title
      Add a caregiver to an existing user
    = form_with(url: create_share_path, local: true) do |f|
      .form-label.margin-bottom-10
        Caregiver for
      - select_options = options_from_collection_for_select(@users, 'id', 'name_and_email')
      = f.select(:sharer_id, select_options, {include_blank: true}, {class: 'form-input select-css margin-bottom-10'})

      .form-label.margin-bottom-10
        Caregiver
      - select_options = options_from_collection_for_select(@caregivers, 'id', 'name_and_email')
      = f.select(:cg, select_options, {include_blank: true}, {class: 'form-input select-css margin-bottom-10'})

      .margin-top-15
        = f.submit 'Create caregiver', class: 'button'

    .margin-top-15
      = button_to 'Cancel', admin_path, class: 'button', method: :get

    %div{style: 'height:200px'}

app/views/admin/index.html.haml
#admin-index
  - if current_user.org
    - current_email_address = current_user.org.contact_email_address
    #contact-email-address
      Contact:
      #contact-email-address-display= current_email_address
      #open-email-address-editor= inline_svg('edit.svg', class: 'contact-email-svg')
      #contact-email-address-editor.hidden{'data-org-id': current_user.org.id}
        %span= email_field_tag('contact_email_address', current_email_address, autofocus: true, placeholder: current_email_address, id: 'contact-email-address-value')
        %span#update-contact-email-address= inline_svg('check.svg', class: 'contact-email-svg')
        %span#cancel-edit-contact-email-address= inline_svg('x.svg', class: 'contact-email-svg')
  - else 
    .margin-top-20 
  #admin-action-links
    .admin-link-container= link_to 'Invite New User by Email', new_user_invitation_path, class: 'form-link medium', method: :get
    .admin-link-container= link_to 'Create and Switch to New User Now', new_registration_path, class: 'form-link medium', method: :get
    .admin-link-container= link_to 'Create Caregiver Account', new_caregiver_path, class: 'form-link medium', method: :get
    .admin-link-container= link_to 'Switch to Existing User', switch_user_select_path, class: 'form-link medium', method: :get
    - if current_user.root?
      .admin-link-container= button_to 'Create New Organization', new_org_path, class: 'form-link medium', method: :get

  #admin-table-container
    %table#user-table.tablesorter-custom
      %thead
        %tr
          - if current_user.root?
            %th Org
          %th
            Participant
            %br
            (*caregiver)
          %th Phone number
          %th REDCap ID
          %td Follow-up apppointment date
          %th
            Logins: last
            %br
            (excluding initial visit)
          %th Recording: clicks on play
      %tbody
        - current_user.viewable_users.each do |user|
          - last_login_at =  format_date_time(user.current_sign_in_at || user.last_sign_in_at)
          - is_admin = user.privileged?
          - last_login_string = user.corrected_sign_ins == 0 ? '' : ": #{last_login_at}"
          - followup_message = user.recordings.last&.followup_message
          - followup_date = followup_message ? 3.days.after(followup_message.deliver_at) : nil
          - show_followup_date = followup_date && (1.year.from_now - followup_date).to_i  > 0
          - followup_date_editable = followup_date && followup_message.delivered_at.nil? 
          %tr.table-row.hidden
          %tr{'data-is-admin': is_admin, class: "table-row #{is_admin ? 'hidden' : ''}"}
            - if current_user.root?
              %td= user.org&.name
            %td
              = "#{user.full_name}#{user.created_as_caregiver ? '*' : ''}"
              %br
              %span.italic-note=user.email
            %td= render partial: 'editable', locals: {value: user.phone_number, post_path: 'update_phone_number', user: user, input_class: 'phone-number'}
            %td= render partial: 'editable', locals: {value: user.participant&.redcap_id, post_path: 'update_redcap_id', user: user, input_class: ''}
            - if followup_date_editable
              %td= render partial: 'editable', locals: {value: show_followup_date ? format_date(followup_date) : '', post_path: 'update_followup_message', user: user, input_class: 'datepicker'}
            - elsif show_followup_date
              %td
                .margin-top-10= format_date(followup_date) 
            - else 
              %td
            %td= "#{user.corrected_sign_ins}#{last_login_string}" 
            %td
              - if user.recordings.any?
                - user.recordings.order(created_at: :desc).each do |recording|
                  .admin-recording-link{'data-recording-id': recording.id}= "#{format_date_time(recording.created_at)}: #{recording.total_clicks_on_play}"

app/views/admin/manage_recordings.html.haml
.table-container
  %table.table.table-striped.tablesorter{:"data-sort-column" => 0, :"data-sort-desc" => 1}
    %thead
      %tr
        %th Recorded at (click to view)
        %th Database ID
        %th Recorded By
        %th Audit complete
    %tbody
      - @recordings.all.each do |recording|
        %tr.trecording-select
          %td.recording-select{data: {href: play_path(recording.id)}}= link_to format_date_time_sort(recording.created_at), play_path(recording.id)
          %td= recording.id
          %td.recording-select{data: {href: play_path(recording.id)}}= recording.user.email
          - if recording.user_can_access
            %td.table-check= fa_icon 'check'
          -else
            %td

app/views/admin/new_caregiver.html.haml
.pad-30.horizontal-center
  #new-caregiver-form.centered-form-container
    %p.form-title
      Enter information for new caregiver account
    = form_with(url: create_caregiver_path, local: true, class: 'overflow-scroll') do |f|
      .form-label.margin-bottom-10
        Caregiver for
      - select_options = options_from_collection_for_select(@users, 'id', 'name_and_email')
      = f.select(:sharer_id, select_options, {include_blank: true}, {class: 'form-input select-css margin-bottom-10'})

      - if current_user.root?
        .form-label.margin-bottom-10 Organization
        - select_options = options_from_collection_for_select(@orgs, 'id', 'name')
        = f.select(:org_id, select_options, {include_blank: true}, {class: 'form-input select-css margin-bottom-10'})

      .form-label.invisible= t(:first_name)
      = f.text_field :first_name,
        class: 'form-input',
        placeholder: t(:first_name),
        data: {placeholder: t(:first_name)}
      .input-underscore-tight

      .form-label.invisible= t(:last_name)
      = f.text_field :last_name,
        class: 'form-input',
        placeholder: t(:last_name),
        data: {placeholder: t(:last_name)}
      .input-underscore-tight

      .form-label.invisible= t(:email_address)
      = f.email_field :email,
        class: 'form-input',
        placeholder: t(:email_address),
        data: {placeholder: t(:email)}
      .input-underscore-tight

      .form-label= t(:phone_number)
      = f.text_field :phone_number,
        class: 'form-input phone-number',
        placeholder: t(:phone_number)
      .input-underscore

      .margin-top-15
        = f.submit 'Create caregiver', class: 'button'

    .margin-top-15
      = button_to 'Cancel', admin_path, class: 'button', method: :get

    %div{style: 'height:200px'}

app/views/admin/new_org.html.haml
#new-org-form.centered-form-container
  %p.form-title
    Enter information for new organization
  = form_for(Org.new, url: create_org_path) do |f|
    .form-field-container.field-centered
      .form-label.margin-top-20
        Organization name
      = f.text_field :name, class: 'form-input'
    .form-field-container.field-centered
      .form-label.margin-top-20
        Contact email address
      = f.email_field :contact_email_address, class: 'form-input'
    .form-field-container.field-centered
      .margin-top-20
        = f.submit 'Create organization', class: 'button'
  .form-field-container.field-centered
    .margin-top-15
      = button_to 'Cancel', admin_path, class: 'button', method: :get

app/views/admin/new_registration.html.haml
.pad-30.horizontal-center
  #new-registration-form.centered-form-container
    %p.form-title
      Enter information for new user
    = form_for(@user, url: set_password_path) do |f|
      // timezone string will be replaced by JS onload. See user.js
      = f.hidden_field :timezone, value: 'America/New_York'
      .form-label= t(:first_name)
      = f.text_field :first_name,
        class: 'form-input',
        autofocus: true,
        placeholder: t(:first_name),
        data: {placeholder: t(:first_name)}
      .input-underscore

      .form-label= t(:last_name)
      = f.text_field :last_name,
        class: 'form-input',
        placeholder: t(:last_name),
        data: {placeholder: t(:last_name)}
      .input-underscore

      .form-label= t(:email)
      = f.email_field :email,
        class: 'form-input email-input',
        placeholder: t(:email_address),
        data: {placeholder: t(:email_address)}
      .input-underscore

      .form-label= t(:phone_number)
      = f.text_field :phone_number,
        class: 'form-input phone-number',
        placeholder: t(:phone_number)
      .input-underscore

      .form-label Select a caregiver
      - select_options = options_from_collection_for_select(@caregivers, 'id', 'name_and_email')
      = select_tag "cg", select_options, include_blank: true, class: 'margin-bottom-20 select-css'

      - if current_user.root?
        .form-label Organization
        = f.collection_select(:org_id, @orgs, :id, :name, {include_blank: true}, {class: 'margin-bottom-20 select-css'})

      = f.submit 'Next', class: 'button margin-bottom-20'

    = button_to 'Cancel', admin_path, class: 'button', method: :get
   
    %div{style: 'height:200px'}

app/views/admin/set_password.html.haml
.pad-30.horizontal-center.margin-top-40
  .centered-form-container
    %p.form-title Enter a password for your account
    = form_for(@user, url: create_registration_path) do |f|
      = f.hidden_field :first_name, value: @user.first_name
      = f.hidden_field :last_name, value: @user.last_name
      = f.hidden_field :email, value: @user.email
      = f.hidden_field :phone_number, value: @user.phone_number
      = f.hidden_field :org_id, value: @user.org_id
      = f.hidden_field :timezone, value: @user.timezone
      .form-label= t(:new_user_password)
      = f.password_field :password,
        class: 'form-input password-input',
        autofocus: true,
        placeholder: t(:new_user_password),
        data: {placeholder: t(:new_user_password)}
      .input-underscore
      .margin-top-20
        = f.submit 'Create and Switch to New User', class: 'button'
      .margin-top-20
        = button_to 'Cancel', admin_path, class: 'button', method: :get

app/views/admin/switch_user_select.html.haml
#switch-user-form.centered-form-container
  %p.form-title
    Select a user to switch to
  = form_with(url: switch_to_user_path, local: true) do |f|
    .form-field-container.field-centered
      - select_options = options_from_collection_for_select(@users, 'id', 'name_and_email')
      .margin-top-20= f.select(:user_id, select_options, {include_blank: true}, {class: 'form-input select-css'})
    .form-field-container.field-centered
      .margin-top-40= f.submit 'Submit', class: 'button'
  .form-field-container.field-centered
    .margin-top-20= button_to 'Cancel', admin_path, class: 'button', method: :get

app/views/admin/tag_recording.html.haml
1) Diagnosis<br>
2) Discussion of medications<br>
3) Education<br>
4) Follow-ups<br>
5) Recommendation<br>
6) Signs, Symptoms and Problems<br>
7) Test and Imaging Results<br>
8) Treatment Options<br>

%table
  %th
    %tr
      %td text
      %td tags
      %td new tag
      %td links
  - @recording.utterances.each do |u|
    %tr
      %td= u.text
      %td
        - u.tags.each do |t|
          %div="#{t.id} #{t.label}"

      %td 
        = form_for :tag do |f|
          = f.hidden_field :utterance_id, {value: u.id}
          = f.label :tag_type_id
          = f.number_field :tag_type_id
          = f.submit