config/routes.rb
Rails.application.routes.draw do

  # TODO Clean this file up. Make it resourceful.

  devise_for :users, controllers: {invitations: 'invitations'}

  root 'home#index'

  resources :recordings
  resources :tags
  resources :links
  resources :utterances
  resources :clicks, only: [:create]

  get 'toggle_locale',                 to: 'home#toggle_locale',                 as: 'toggle_locale'
  post 'set_locale_cookie',            to: 'application#set_locale_cookie',      as: 'set_locale_cookie'

  post 'destroy_tags/:id',             to: 'tags#destroy_for_utterance',         as: 'destroy_tags'
  post 'destroy_links/:id',            to: 'links#destroy_for_utterance',        as: 'destroy_links'

  # Admin
  get 'admin',                         to: 'admin#index'
  get 'manage_recordings',             to: 'admin#manage_recordings',            as: 'manage_recordings'
  get 'tag_recording/:id',             to: 'admin#tag_recording',                as: 'tag_recording'
  get 'users',                         to: 'admin#users'
  get 'toggle_active/:id',             to: 'admin#toggle_active',                as: 'toggle_active'
  get 'toggle_can_record/:id',         to: 'admin#toggle_can_record',            as: 'toggle_can_record'
  get 'toggle_otp/:id',                to: 'admin#toggle_otp',                   as: 'toggle_otp'
  get 'add_caregiver',                 to: 'admin#add_caregiver'
  post 'create_share',                 to: 'admin#create_share'
  get 'new_registration',              to: 'admin#new_registration'
  post 'set_password',                 to: 'admin#set_password'
  post 'create_registration',          to: 'admin#create_registration'
  get 'switch_user_select',            to: 'admin#switch_user_select'
  post 'switch_to_user',               to: 'admin#switch_to_user'
  get 'new_caregiver',                 to: 'admin#new_caregiver'
  post 'create_caregiver',             to: 'admin#create_caregiver'
  get 'new_org',                       to: 'admin#new_org',                      as: 'new_org'
  post 'create_org',                   to: 'admin#create_org',                   as: 'create_org'
  post 'update_contact_email_address', to: 'admin#update_contact_email_address', as: 'update_contact_email_address'
  post 'update_redcap_id',             to: 'admin#update_redcap_id',             as: 'update_redcap_id'
  post 'update_phone_number',          to: 'admin#update_phone_number',          as: 'update_phone_number'
  post 'update_followup_message',      to: 'admin#update_followup_message',      as: 'update_followup_message'

  # Reports (Admin)
  get 'dashboard',                     to: 'reports#dashboard',                  as: 'dashboard'

  # Recording
  get 'record',                        to: 'record#new'
  get 'file_upload',                   to: 'record#file_upload',                 as: 'file_upload'
  post 'upload',                       to: 'record#upload',                      as: 'upload'
  post 'upload_file',                  to: 'record#upload_file',                 as: 'upload_file'
  get 'recording_saved',               to: 'record#saved'
  get 'upload_transcript',             to: 'record#upload_transcript',           as: 'upload_transcript'
  post 'create_utterances',            to: 'record#create_utterances',           as: 'create_utterances'

  # Recordings
  get 'get_metadata/:id',              to: 'recordings#get_metadata',            as: 'get_metadata'
  post 'update_metadata',              to: 'recordings#update_metadata',         as: 'update_metadata'
  get 'get_notes/:id',                 to: 'recordings#get_notes',               as: 'get_notes'
  post 'upsert_note',                  to: 'recordings#upsert_note',             as: 'upsert_note'
  post 'delete_note',                  to: 'recordings#delete_note',             as: 'delete_note'

  # Playback
  get 'play(/:id)',                    to: 'play#index',                         as: 'play'

  # Sharing
  resources :shares, controller: :share
  get 'no_shares',                     to: 'share#no_shares',                    as: 'no_shares'
  get 'twilio/sms',                    to: 'twilio#sms'

  # Help
  get 'help',                          to: 'help#index',                         as: 'help'
  get 'intro_video',                   to: 'help#intro_video',                   as: 'intro_video'
  get 'dont_onboard',                  to: 'help#dont_onboard',                  as: 'dont_onboard'
  get 'set_onboarded',                 to: 'help#set_onboarded',                 as: 'set_onboarded'
  get 'play/view_transcript/:id',      to: 'help#view_transcript',               as: 'view_transcript'

  # Analytics
  get 'analytics(/:id)',               to: 'analytics#index',                    as: 'analytics'

end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  # A reminder for parsing (some generation of) transcript JSON from AWS
  # json.first['alternatives'].first['words'].first['start_time']['seconds']

  # TODO: Handle non-user roles
  #       Handle non-existant recording ids
  #       Handle non-existant media files
  # Has two forms, with and without an intial recording ID on page load:
  #   - HTML request without a recording ID: /my_recordings (@recording will be nil)
  #   - HTML request with a recording ID: /my_recordings/45
  def index
    @recording = Recording.find_by(id: params[:id])
    @recordings = current_user.viewable_recordings
    @recordings_by_user = current_user.viewable_recordings_by_user_date
  end

  private

  # NOTE: Disabled because tag table is currently disabled
  # Merges contiguous utterances that have the same tag(s)
  # def prepare_utterances(recording)
  #   return_utterances = []
  #   multi_utterance = nil
  #   utterances = recording.utterances.order(:index)
  #   utterances.each do |utterance|
  #     if utterance.tags.any?
  #       utterance.tmp_tag_types = utterance.tag_types
  #       multi_utterance = utterance if multi_utterance.nil?
  #       if utterance.tmp_tag_types == multi_utterance.tmp_tag_types
  #         multi_utterance.text += " #{utterance.text}"
  #         multi_utterance.ends_at = utterance.ends_at
  #         multi_utterance.links += utterance.links
  #       else
  #         return_utterances << multi_utterance unless multi_utterance.nil?
  #         multi_utterance = utterance
  #       end
  #       puts return_utterances.map{|u| u.id}
  #     end
  #   end
  #   return_utterances << multi_utterance unless multi_utterance.nil?
  #   return_utterances
  # end

end

app/views/play/_filter_help.html.haml
#filter-help-text
  %p.help-text
    %h3 The colored buttons allow you control which aspects of your visit that you want to focus on. The buttons are:
  %p.help-text
    %ul#help-list
      %li.help-text
        %b Symptoms signs problems:
        A symptom or sign of your health is discussed
      %li.help-text
        %b Diagnosis:
        A possible diagnosis is discussed  
      %li.help-text
        %b Medication:
        A medication is discussed
      %li.help-text
        %b Test &amp; Imaging:
        A test or imaging result is discussed
      %li.help-text
        %b Recommendation:
        The doctor recommends or confirms an approach to your healthcare
      %li.help-text
        %b Follow-up:
        A follow-up plan or future visit is discussed  
      %li.help-text
        %b Education:
        The doctor explains something about your health e.g. what a medicine does,
      %li.help-text
        %b Treatment options:
        Different treatment options, including doing nothing are discussed  
  %p.help-text#close-filter-help
    %button.btn.btn-primary Close

app/views/play/_recording_list_item.haml
.recording-list-item.log(id="select-recording-#{recording.id}" data-recording-id="#{recording.id}")
  .recording-description
    .svg-padding
    = inline_svg('file-earmark-play-fill.svg', class: 'icon-svg')
    .recording-title= recording.title
    - if recording.provider
      .recording-provider.italic-note= recording.provider
  .recording-date
    .recording-date= minimal_date(recording.created_at)
    .recoording-days-ago.italic-note= days_ago(recording.created_at)

app/views/play/_recording_table.haml
.recording-table-container(data-user-id="#{rec_array[0][0][0].user_id}")
  %table
    %tbody
      - rec_array.each do |year_array|
        %tr.table-row.year.list-item.vis 
          %td
            .recording-year
              = inline_svg('play.svg', class: 'expand-svg')
              .svg-padding
              = inline_svg('folder-fill.svg', class: 'icon-svg')
              .year-title= year_array[0][0].created_at.strftime("%Y Appointments")
        %tr.table-row
          %td
            .table-wrapper.hidden
              %table
                %tbody
                  - year_array.each do |month_array|
                    %tr.table-row.month.list-item
                      %td
                        .recording-month
                          = inline_svg('play.svg', class: 'expand-svg')
                          .svg-padding
                          = inline_svg('folder-fill.svg', class: 'icon-svg')
                          .month-title= month_array[0].created_at.strftime("%B Appointments")
                    %tr.table-row
                      %td
                        .table-wrapper.hidden
                          %table
                            %tbody
                              - month_array.each do |recording|
                                %tr.table-row.rec.list-item
                                  %td
                                    = render 'recording_list_item', recording: recording

app/views/play/_video_element.html.haml
= video_tag(url_for(Recording.find(recording_id).media_file),
  id: 'video-element',
  'data-recording-id': @recording.id,
  'data-is-video': @recording.is_video,
  class: 'hidden',
  controls: false)

app/views/play/index.html.haml
#play-view{'data-initial-recording-id': @recording&.id}
  #metadata-overlay.overlay.invisible
    .modal-form-container
      %form#metadata-form
        .form-title.margin-bottom-10= t(:edit_recording_details)
        .form-label= t(:recording_name)
        = text_field_tag('edit-recording-title', nil, value: @recording&.title, placeholder: t(:recording_name), class: 'form-input', data: {placeholder: t(:recording_name)})
        .input-underscore
        .form-label= t(:doctors_name)
        = text_field_tag('edit-recording-provider', nil, value: @recording&.provider, placeholder: t(:doctors_name), class: 'form-input', data: {placeholder: t(:doctors_name)})
        .input-underscore
        .save-cancel-buttons
          #metadata-cancel.cancel.modal-cancel= t(:cancel)
          #metadata-save.save.modal-save.enter-submit= t(:save)
  -# #note-overlay.overlay.invisible
  -#   .modal-form-container
  -#     %form#note-form
  -#       #note-form-title.form-title.margin-bottom-10
  -#         = t(:new_note_at)
  -#         %span#note-time
  -#       = text_area_tag('edit-note-text', nil, value: nil, placeholder: t(:enter_note_here), class: 'form-input-area')
  -#       .save-cancel-buttons
  -#         #note-cancel.cancel.modal-cancel= t(:cancel)
  -#         #note-save.save.modal-save= t(:save)
  #left
    - if @recordings_by_user.any?
      #search-and-select
        #select-header= t(:select_a_recording)
        #select
          - @recordings_by_user.each do |user_and_recordings|
            - user = user_and_recordings[:user]
            - if user.first_name && user.last_name
              - user_name = "#{user.first_name.titlecase} #{user&.last_name.titlecase}"
            - elsif user.email
              - user_name = user.email
            - else
              - user_name = 'No user name found!'
            - unless user == current_user && @recordings_by_user.length == 1
              .recording-owner= user_name
            = render 'recording_table', rec_array: user_and_recordings[:recordings_by_date]
    -else
      #no-recordings
        .pad-30= t(:recordings_appear_here)
        - if current_user.can_record
          =link_to t(:make_recording_now), record_path, class: 'button'
  #right
    #player-container
      #header
        #edit-recording-metadata.log
          #recording-title
          #metadata-edit-icon
            #recording-provider
            = inline_svg('edit.svg', class: 'edit-svg')
        #header-right
          #recording-date
          #recording-days-ago
      -# #notes-header.hidden= t(:your_notes)
      -# #notes
      -#   #no-notes= t(:notes_appear_here)
      -#   #notes-container.hidden
      #video-container
      #player
        -# #create-note.log
        -#   = inline_svg('plus.svg', class: 'small-svg')
        -#   %span#create-note-text.text-with-svg= t(:new_note_at)
        -#   %span#create-note-time.text-with-svg 00:00
        #timeline-container
          #timeline.log
          #progress-bar
          #playhead.log
        #time
          %span#current-time
            00:00
          %span#duration
            00:00
        #player-button-container
          #rewind-button.player-button-left.log
            = inline_svg('skip_to_start.svg', class: 'player-button-svg-left')
            .player-button-label-left= t(:rewind)
          #back-button.player-button.log
            = inline_svg('step_back.svg', class: 'player-button-svg')
            .player-button-label= t(:back_10_sec )
          #play-pause-button.player-button.log
            = inline_svg('play.svg', id: 'play-glyph', class: 'player-button-svg')
            = inline_svg('pause.svg', id: 'pause-glyph', class: 'player-button-svg hidden')
            #play-label.player-button-label= t(:play)
            #pause-label.player-button-label.hidden= t(:pause)
          #forward-button.player-button.log
            = inline_svg('step_forward.svg', class: 'player-button-svg')
            .player-button-label= t(:forward_10_sec)
          #mute-button.player-button-right.log
            = inline_svg('volume_off.svg', id: 'mute-glyph', class: 'player-button-svg-right')
            = inline_svg('volume_max.svg', id: 'unmute-glyph', class: 'player-button-svg-right hidden')
            #mute-label.player-button-label-right= t(:mute)
            #unmute-label.player-button-label-right.hidden= t(:unmute)
      #toolbar
        #show-select
          = inline_svg('arrow-left.svg', class: 'small-svg')
          %span.text-with-svg= t(:select_a_recording)
    #recording-is-not-processed
      .margin-top-150
        .title.text-center Your recording will be ready in a few minutes
        .margin-top-40.text-center= inline_svg('alert.svg', class: 'alert-svg')
      #toolbar
        #show-select
          = inline_svg('arrow-left.svg', class: 'small-svg')
          %span.text-with-svg= t(:select_a_recording)

app/views/play/play.html.haml
-# Conditional ID to handle different grid layouts between audio and video
.invisible{id: @view_id}

  .summary-overlay.invisible
    #summary-container
      #close-summary= fa_icon 'times'
      #summary-title
        #summary-title-text
      #summary
      #concept-link
        %a#concept-link-text.plain-link{target: '_blank'} Visit medlineplus.gov to learn more

  #video-container
    - if @recording.is_video?
      #loader-container
        %h3 Loading media. This could take a few minutes...
        #loader
    = video_tag(url_for(@recording.media_file),
      id: 'video-element',
      'data-recording-id': @recording.id,
      'data-is-video': @recording.is_video,
      class: 'hidden',
      controls: false)

  #header-container
    #header
      #title= @title
      #provider.user-field-container
        .user-field-label
          = t(:provider)
          .save.hidden= t(:save)
          .cancel.hidden= t(:cancel)
        %input#provider-content.user-field-content{'data-recording-id': @recording.id, 'data-type': @provider.type, value: @provider.text}
      #note.user-field-container
        .user-field-label
          = t(:notes)
          .save.hidden= t(:save)
          .cancel.hidden= t(:cancel)
        %textarea#note-content.user-field-content.text-area{'data-recording-id': @recording.id, 'data-type': @note.type}
          = @note.text

      -# Admin-only editing affordances
      -#########################################################################################
      - if current_user.privileged?
        #editing-container
          .edit-row
            #enable-editing.edit-check
              %svg#editing-glyph.concept-glyph.check-glyph.svg.fill-white.hidden{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
                %path#check{:d => "M27.37592,9.70459l-14.151,15.97693a.99985.99985,0,0,1-1.47558.02356L4.59711,18.1322a.99992.99992,0,0,1-.05384-1.31128L5.495,15.63123a.99994.99994,0,0,1,1.22808-.26966L12,18,24.79724,7.09863a.99991.99991,0,0,1,1.35553.0542l1.1817,1.18164A1,1,0,0,1,27.37592,9.70459Z"}
            Enable annotation/link deletion
          .edit-row
            - if !@recording.user_can_access && !@recording.user.can_view_tags.nil?
              #audit-complete Mark as audited and send email to user
            - if @recording.user.can_view_tags.nil?
              #audit-premature User must be assigned to a study arm before audit can be marked complete

      -#########################################################################################

  #player
    #controls-container
      #timeline.track
        #progress-bar
        #playhead.track
        #time
          #current-time
            00:00
          #duration
            00:00
      #buttons-container
        #rewind-button.player-button.track
          .centered-glyph= fa_icon 'fast-backward'
          %span.button-label= t(:rewind)

        #back-button.player-button.track
          .centered-glyph= fa_icon 'undo'
          %span.button-label= t(:back_10_sec )

        #play-pause-button.player-button.track
          .centered-glyph
            #pause-glyph.invisible.shift-right= fa_icon 'pause'
            #play-glyph.shift-left= fa_icon 'play'
          .full-center
            #play-label.absolute.play-pause-label
              %span.button-label= t(:play)
            #pause-label.invisible.absolute.play-pause-label
              %span.button-label= t(:pause)

        #forward-button.player-button.track
          .centered-glyph.mirror-horiz= fa_icon 'undo'
          %span.button-label= t(:forward_10_sec)

        #mute-button.player-button.track
          .centered-glyph
            #unmute-glyph.hidden= fa_icon 'volume-up'
            #mute-glyph= fa_icon 'volume-mute'
          %span#mute-label
            %span.button-label= t(:mute)
          %span#unmute-label.hidden
            %span.button-label= t(:unmute)
  - if current_user.can_view_tags || current_user.privileged?
    #tag-table
      %table
        %thead
          %tr#header-row
            %th= t(:start_end)
            %th Listen to the medical topic discussed from your visit
        %tbody
          %tr#empty-result-message.hidden
            %td{align: 'center', colspan: 3}
              = t(:no_results)
          - @segments.each do |segment|
            - if segment.tmp_annotation_categories.any?
              - tag_types = segment.tmp_annotation_categories.map{|c| TagType.find_by(label: c)}
              %tr.tag-row.tag-row-hover{'data-tag-type-ids': tag_types.map{|t| t.id},
                'data-annotation-concepts': segment.tmp_annotations.map{|a| a.text},
                'data-text': segment.tmp_text,
                'data-start-time': segment.start_time,
                'data-end-time': segment.end_time}
                %td.tag-cell.click-to-seek.track.time-link-container{'data-start-time': segment.start_time}
                  .time-link= "#{mm_ss(segment.start_time)} - #{mm_ss(segment.end_time)}"
                  .big-play-button= fa_icon 'play'
                %td.tag-cell.click-to-seek.track{'data-start-time': segment.start_time}
                  .annotation-list
                    - tag_types.each do |tag_type|
                      .tag-container
                        .filter-circle.margin-top-8{class: "filter-#{tag_type.id}"}
                        .tag
                          %span.category= "#{tag_type.label.titleize}:"
                          - concepts = segment.tmp_annotations.select{|a| a.category == tag_type.label}.map{|a| a.text.downcase}.uniq
                          - concepts.each do |concept|
                            %span.concept= "#{concept.titleize}#{concept == concepts.last ? '' : ', '}"
            - else
              %tr.hidden
                %td.tag-cell.hidden{'data-start-time': segment.start_time}
                %td.tag-cell.hidden{'data-start-time': segment.start_time}

    #sidebar
      -# Filtering is disabled
      -# .filter-header Search
      -# .filter-sub-header Enter a word mentioned during your clinic visit and find it in the audio recording
      -# #search-container
      -#   %input#search-input
      -#     = fa_icon 'search', id: 'search-icon'
      -#     = fa_icon 'times-circle', id: 'close-icon', class: 'hidden'

      .filter-header Medical Topic
      .filter-sub-header Select the medical information that you want to find from your clinic visit
      #filter-container
        #filters
          - @grouped_annotations.each do |tag_type_hash|
            - tag_type = tag_type_hash.keys.first
            - annotations = tag_type_hash[tag_type]
            - annotation_texts = []
            .filter
              .category-container{class: "#{annotations.any? ? 'category-has-annotations': nil}"}
                .expand-category{class: "#{annotations.any? ? nil : 'grayout'}"}
                  = inline_svg('glyphicons-basic-175-play.svg', class: 'expand-svg')
                  .expand-label= annotations.any? ? 'see more' : 'none'
                .filter-button{'data-tag-type-id': tag_type.id}
                  .filter-check{class: "#{annotations.any? ? nil : 'grayout'}"}
                    %svg.check-glyph.svg.hidden{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
                      %path#check{:d => "M27.37592,9.70459l-14.151,15.97693a.99985.99985,0,0,1-1.47558.02356L4.59711,18.1322a.99992.99992,0,0,1-.05384-1.31128L5.495,15.63123a.99994.99994,0,0,1,1.22808-.26966L12,18,24.79724,7.09863a.99991.99991,0,0,1,1.35553.0542l1.1817,1.18164A1,1,0,0,1,27.37592,9.70459Z"}
                  .filter-label{class: "#{annotations.any? ? nil : 'grayout'}"}
                    .filter-circle{class: "#{annotations.any? ? ('filter-' + tag_type.id.to_s) : 'gray-background'}"}
                    .filter-label-text= t(tag_type.label)
              .concepts-container.hidden
                - annotations.each do |annotation|
                  - unless annotation_texts.include?(annotation.text)
                    - annotation_texts << annotation.text
                    .concept-container
                      .concept-filter{'data-concept-text': annotation.text}
                        .concept-check
                          %svg.concept-glyph.check-glyph.svg.hidden{:viewbox => "0 0 28 28", :xmlns => "http://www.w3.org/2000/svg"}
                            %path#check{:d => "M27.37592,9.70459l-14.151,15.97693a.99985.99985,0,0,1-1.47558.02356L4.59711,18.1322a.99992.99992,0,0,1-.05384-1.31128L5.495,15.63123a.99994.99994,0,0,1,1.22808-.26966L12,18,24.79724,7.09863a.99991.99991,0,0,1,1.35553.0542l1.1817,1.18164A1,1,0,0,1,27.37592,9.70459Z"}
                        .concept-label
                          = annotation.text.titleize
                      - if current_user.privileged?
                        .deleteable.delete-annotation{'data-annotation-id': annotation.id}= fa_icon 'times-circle'
                      - if annotation.medline_url
                        .concept-link{'data-title': annotation.text.titleize, 'data-summary': annotation.medline_summary, 'data-url': annotation.medline_url} Learn More
                        - if current_user.privileged?
                          .deleteable.delete-link{'data-annotation-id': annotation.id}= fa_icon 'times-circle'
        #show-all-topics Clear
.overlay.hidden