config/routes.rb
Rails.application.routes.draw do

  # TODO Clean this file up. Make it resourceful.

  devise_for :users, controllers: {invitations: 'invitations'}

  root 'home#index'

  resources :recordings
  resources :tags
  resources :links
  resources :utterances
  resources :clicks, only: [:create]

  get 'toggle_locale',                 to: 'home#toggle_locale',                 as: 'toggle_locale'
  post 'set_locale_cookie',            to: 'application#set_locale_cookie',      as: 'set_locale_cookie'

  post 'destroy_tags/:id',             to: 'tags#destroy_for_utterance',         as: 'destroy_tags'
  post 'destroy_links/:id',            to: 'links#destroy_for_utterance',        as: 'destroy_links'

  # Admin
  get 'admin',                         to: 'admin#index'
  get 'manage_recordings',             to: 'admin#manage_recordings',            as: 'manage_recordings'
  get 'tag_recording/:id',             to: 'admin#tag_recording',                as: 'tag_recording'
  get 'users',                         to: 'admin#users'
  get 'toggle_active/:id',             to: 'admin#toggle_active',                as: 'toggle_active'
  get 'toggle_can_record/:id',         to: 'admin#toggle_can_record',            as: 'toggle_can_record'
  get 'toggle_otp/:id',                to: 'admin#toggle_otp',                   as: 'toggle_otp'
  get 'add_caregiver',                 to: 'admin#add_caregiver'
  post 'create_share',                 to: 'admin#create_share'
  get 'new_registration',              to: 'admin#new_registration'
  post 'set_password',                 to: 'admin#set_password'
  post 'create_registration',          to: 'admin#create_registration'
  get 'switch_user_select',            to: 'admin#switch_user_select'
  post 'switch_to_user',               to: 'admin#switch_to_user'
  get 'new_caregiver',                 to: 'admin#new_caregiver'
  post 'create_caregiver',             to: 'admin#create_caregiver'
  get 'new_org',                       to: 'admin#new_org',                      as: 'new_org'
  post 'create_org',                   to: 'admin#create_org',                   as: 'create_org'
  post 'update_contact_email_address', to: 'admin#update_contact_email_address', as: 'update_contact_email_address'
  post 'update_redcap_id',             to: 'admin#update_redcap_id',             as: 'update_redcap_id'
  post 'update_phone_number',          to: 'admin#update_phone_number',          as: 'update_phone_number'
  post 'update_followup_message',      to: 'admin#update_followup_message',      as: 'update_followup_message'

  # Reports (Admin)
  get 'dashboard',                     to: 'reports#dashboard',                  as: 'dashboard'

  # Recording
  get 'record',                        to: 'record#new'
  get 'file_upload',                   to: 'record#file_upload',                 as: 'file_upload'
  post 'upload',                       to: 'record#upload',                      as: 'upload'
  post 'upload_file',                  to: 'record#upload_file',                 as: 'upload_file'
  get 'recording_saved',               to: 'record#saved'
  get 'upload_transcript',             to: 'record#upload_transcript',           as: 'upload_transcript'
  post 'create_utterances',            to: 'record#create_utterances',           as: 'create_utterances'

  # Recordings
  get 'get_metadata/:id',              to: 'recordings#get_metadata',            as: 'get_metadata'
  post 'update_metadata',              to: 'recordings#update_metadata',         as: 'update_metadata'
  get 'get_notes/:id',                 to: 'recordings#get_notes',               as: 'get_notes'
  post 'upsert_note',                  to: 'recordings#upsert_note',             as: 'upsert_note'
  post 'delete_note',                  to: 'recordings#delete_note',             as: 'delete_note'

  # Playback
  get 'play(/:id)',                    to: 'play#index',                         as: 'play'

  # Sharing
  resources :shares, controller: :share
  get 'no_shares',                     to: 'share#no_shares',                    as: 'no_shares'
  get 'twilio/sms',                    to: 'twilio#sms'

  # Help
  get 'help',                          to: 'help#index',                         as: 'help'
  get 'intro_video',                   to: 'help#intro_video',                   as: 'intro_video'
  get 'dont_onboard',                  to: 'help#dont_onboard',                  as: 'dont_onboard'
  get 'set_onboarded',                 to: 'help#set_onboarded',                 as: 'set_onboarded'
  get 'play/view_transcript/:id',      to: 'help#view_transcript',               as: 'view_transcript'

  # Analytics
  get 'analytics(/:id)',               to: 'analytics#index',                    as: 'analytics'

end

app/controllers/record_controller.rb
class RecordController < ApplicationController

  def new
    redirect_to :root unless current_user.can_record
  end

  # In-app recordings, coming in as AJAX
  def upload
    handle_blob(request.body.read, current_user)
  end

  # View for manually uploading an existing file
  def file_upload
    @recording = Recording.new
    @users = User.regular.map {|u| [u.email, u.id]}
  end

  # Admin-uploaded recordings
  def upload_file
    handle_blob(recording_params[:file].read, User.find_by(id: recording_params[:user]), true)
  end

  # For manually uploading a transcription from a file. Currently supports Acusis format
  def upload_transcript
    begin
      @recording = Recording.find(params[:id])
    rescue
      flash.alert = 'Recording not found.'
      redirect_to managage_recordings_path
    end
    if @recording.utterances.any?
      flash.alert = 'A transcript already exists for this recording.  If you continue, it will be deleted along with all of its tags.'
    end
  end

  private

  # Create a [Recording] record from the passed-in blob
  def handle_blob(blob, user, is_file_upload=false)
    sha1 = Digest::SHA1.hexdigest(blob)
    filepath = "#{Rails.root}/tmp/#{sha1}.ogg"
    File.open(filepath, 'wb') do |disk_file|
      disk_file.write(blob)
    end
    recording = Recording.new(
      user: user,
      sha1: sha1,
      is_video: false,
      media_format: 'mp3',
    )
    recording.media_file.attach(io: File.open(filepath), filename: "#{sha1}.ogg")
    recording.title = default_title
    if recording.save!
      `rm #{filepath}`
      recording.transcribe
      # flash.alert = 'Your recording is being processed. We will email you when it is ready.'
    else
      flash.alert = recording.errors.full_messages
    end
    flash.keep(:alert)
    if is_file_upload
      redirect_to :recordings
    else
      render js: "window.location = 'play'"
    end
  end
  
  def default_title
    case Time.now.in_time_zone(current_user.timezone).hour
    when 0..4
      t(:nighttime_appointment)
    when 5..11
      t(:morning_appointment)
    when 12..16
      t(:afternoon_appointment)
    when 17..19
      t(:evening_appointment)
    when 20..24
      t(:nighttime_appointment)
    end
  end

  def recording_params
    params.require(:recording).permit(:file, :user)
  end

  def transcript_params
    params.permit(:recording_id, :file)
  end

end

app/views/record/file_upload.html.haml
.row
  .col-xs-4
  .col-xs-4
    %h3= 'Upload audio recording'
    = form_for @recording, url: upload_file_path do |f|
      %p= f.select :user, @users, label: 'Upload recording for', include_blank: true
      %p= f.file_field :file, label: 'Currently only .flac files are supported'
      %p= f.submit 'Upload Now', class: 'btn btn-primary'
  .col-xs-4

app/views/record/new.html.haml
%audio#record-audio{autoplay: true}

#no-media-recorder-support.overlay.invisible
  .modal-form-container
    #no-media-recorder-message
      %p.title
        It looks like your web browser doesn't support recording audio.
      %p.margin-bottom-30
        Making recordings is currently not supported on iPhones, iPads, or Mac computers using the Safari web browser.
      .button= link_to 'Take me back to My Recordings', play_path, class: 'no-decoration'

#overlay.overlay.invisible
  #loader-container
    #sized-loader-box
      #loader
    %h3#upload-text= t(:uploading_recording)

#record-container.invisible
  %canvas#audio-meter

  #buttons-and-time
    #time-display
      00:00:00

    #record-buttons-container
      #record-start-button.record-button.log
        = inline_svg('mic.svg', class: 'record-svg')
        .record-button-label
          = t(:start_recording)

      #record-pause-button.record-button-hidden.log
        = inline_svg('pause.svg', class: 'record-svg')
        .record-button-label
          = t(:pause_recording)

      #continue-button.record-button-hidden.log
        = inline_svg('mic.svg', class: 'record-svg')
        .record-button-label
          = t(:continue_recording)

      #save-button.record-button-hidden.log
        = inline_svg('check.svg', class: 'record-svg')
        .record-button-label
          = t(:save_recording)

      #delete-button.record-button-hidden.log
        = inline_svg('x.svg', class: 'record-svg')
        .record-button-label
          = t(:delete_recording)

app/views/record/upload_transcript.html.haml
.centered-form-container
  %h3
    = "Upload transcript for #{@recording.user.email}, recorded #{format_date_time @recording.created_at}"
    %br
  = form_tag({action: :create_utterances}, multipart: true) do
    = hidden_field_tag :recording_id, @recording.id
    %p
      .form-field-container.field-centered
        %h4.form-label
          Select Acusis transcript file (txt format)
        = file_field_tag :file
    %p
      .form-field-container.field-centered
        = submit_tag 'Upload now', class: 'button'
  .form-field-container.field-centered
    = button_to 'Cancel', manage_recordings_path, class: 'button', method: :get