config/routes.rb
Rails.application.routes.draw do

  # TODO Clean this file up. Make it resourceful.

  devise_for :users, controllers: {invitations: 'invitations'}

  root 'home#index'

  resources :recordings
  resources :tags
  resources :links
  resources :utterances
  resources :clicks, only: [:create]

  get 'toggle_locale',                 to: 'home#toggle_locale',                 as: 'toggle_locale'
  post 'set_locale_cookie',            to: 'application#set_locale_cookie',      as: 'set_locale_cookie'

  post 'destroy_tags/:id',             to: 'tags#destroy_for_utterance',         as: 'destroy_tags'
  post 'destroy_links/:id',            to: 'links#destroy_for_utterance',        as: 'destroy_links'

  # Admin
  get 'admin',                         to: 'admin#index'
  get 'manage_recordings',             to: 'admin#manage_recordings',            as: 'manage_recordings'
  get 'tag_recording/:id',             to: 'admin#tag_recording',                as: 'tag_recording'
  get 'users',                         to: 'admin#users'
  get 'toggle_active/:id',             to: 'admin#toggle_active',                as: 'toggle_active'
  get 'toggle_can_record/:id',         to: 'admin#toggle_can_record',            as: 'toggle_can_record'
  get 'toggle_otp/:id',                to: 'admin#toggle_otp',                   as: 'toggle_otp'
  get 'add_caregiver',                 to: 'admin#add_caregiver'
  post 'create_share',                 to: 'admin#create_share'
  get 'new_registration',              to: 'admin#new_registration'
  post 'set_password',                 to: 'admin#set_password'
  post 'create_registration',          to: 'admin#create_registration'
  get 'switch_user_select',            to: 'admin#switch_user_select'
  post 'switch_to_user',               to: 'admin#switch_to_user'
  get 'new_caregiver',                 to: 'admin#new_caregiver'
  post 'create_caregiver',             to: 'admin#create_caregiver'
  get 'new_org',                       to: 'admin#new_org',                      as: 'new_org'
  post 'create_org',                   to: 'admin#create_org',                   as: 'create_org'
  post 'update_contact_email_address', to: 'admin#update_contact_email_address', as: 'update_contact_email_address'
  post 'update_redcap_id',             to: 'admin#update_redcap_id',             as: 'update_redcap_id'
  post 'update_phone_number',          to: 'admin#update_phone_number',          as: 'update_phone_number'
  post 'update_followup_message',      to: 'admin#update_followup_message',      as: 'update_followup_message'

  # Reports (Admin)
  get 'dashboard',                     to: 'reports#dashboard',                  as: 'dashboard'

  # Recording
  get 'record',                        to: 'record#new'
  get 'file_upload',                   to: 'record#file_upload',                 as: 'file_upload'
  post 'upload',                       to: 'record#upload',                      as: 'upload'
  post 'upload_file',                  to: 'record#upload_file',                 as: 'upload_file'
  get 'recording_saved',               to: 'record#saved'
  get 'upload_transcript',             to: 'record#upload_transcript',           as: 'upload_transcript'
  post 'create_utterances',            to: 'record#create_utterances',           as: 'create_utterances'

  # Recordings
  get 'get_metadata/:id',              to: 'recordings#get_metadata',            as: 'get_metadata'
  post 'update_metadata',              to: 'recordings#update_metadata',         as: 'update_metadata'
  get 'get_notes/:id',                 to: 'recordings#get_notes',               as: 'get_notes'
  post 'upsert_note',                  to: 'recordings#upsert_note',             as: 'upsert_note'
  post 'delete_note',                  to: 'recordings#delete_note',             as: 'delete_note'

  # Playback
  get 'play(/:id)',                    to: 'play#index',                         as: 'play'

  # Sharing
  resources :shares, controller: :share
  get 'no_shares',                     to: 'share#no_shares',                    as: 'no_shares'
  get 'twilio/sms',                    to: 'twilio#sms'

  # Help
  get 'help',                          to: 'help#index',                         as: 'help'
  get 'intro_video',                   to: 'help#intro_video',                   as: 'intro_video'
  get 'dont_onboard',                  to: 'help#dont_onboard',                  as: 'dont_onboard'
  get 'set_onboarded',                 to: 'help#set_onboarded',                 as: 'set_onboarded'
  get 'play/view_transcript/:id',      to: 'help#view_transcript',               as: 'view_transcript'

  # Analytics
  get 'analytics(/:id)',               to: 'analytics#index',                    as: 'analytics'

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :utterance
  belongs_to :tag_type

  validates_presence_of :utterance, :tag_type
  validates_uniqueness_of :tag_type, scope: :utterance
end

app/models/tag_type.rb
class TagType < ApplicationRecord
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    tag = Tag.new(
      utterance: Utterance.find_by(id: tag_params[:utterance_id]),
      tag_type: TagType.find_by(id: tag_params[:tag_type_id])
    )
    unless(tag.save)
      flash.alert = tag.errors.full_messages
    end
    redirect_to action: :new, id: tag.utterance.recording.id, utterance_id: tag.utterance.id
  end

  def new
    @recording = Recording.find(params[:id])
    @utterance = Utterance.find_by(id: params[:utterance_id]) || @recording.utterances.first
  end

  def destroy_for_utterance
    utterance = Utterance.find_by(id: params[:id])
    utterance.tags.each{|t| t.destroy}
    redirect_to action: :new, id: utterance.recording.id, utterance_id: utterance.id
  end

  private

  def tag_params
    params.require(:tag).permit(:utterance_id, :tag_type_id)
  end

end

app/views/tags/new.html.haml
:javascript
  window.onload = function(){
    document.getElementById('utterance-' + #{@utterance.id}).scrollIntoView();
  };

.table-container.margin-top-20
  %table
    %thead
      %tr
        %th Index
        %th Text
        %th Tags
        %th Links
    %tbody
      - @recording.utterances.each do |u|
        %tr.table-row{id: "utterance-#{u.id}"}
          %td{style: 'font-size: 40px;'}= u.index
          %td{style: 'max-width: 800px;'}= u.text
          %td
            %p
              - u.tags.each do |t|
                %div= t.tag_type.label
            = form_for Tag.new do |f|
              = f.hidden_field :utterance_id, {value: u.id}
              %div= f.select :tag_type_id, options_from_collection_for_select(TagType.all, 'id', 'label'), {include_blank: true}, {class: 'select-css margin-bottom-10'}
              %div= f.submit class: 'button button-short'
            = button_to 'Delete all tags', destroy_tags_path(u.id)
          %td
            %p
              - u.links.each do |l|
                %div= "#{l.label} => #{l.url}"
            = form_for Link.new do |f|
              = f.hidden_field :utterance_id, {value: u.id}
              %div
                = f.text_field :label, class: 'form-input-short'
                Label
              %div
                = f.text_field :url, class: 'form-input-short'
                URL
              = f.submit class: 'button button-short'
            = button_to 'Delete all links', destroy_links_path(u.id)